#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const PACKAGE_ROOT = path.dirname(fileURLToPath(new URL(".", import.meta.url)));
const REPO_ROOT = path.resolve(PACKAGE_ROOT, "../..");
const OUT_DIR = path.join(REPO_ROOT, "contracts/out");
const ABI_DIR = path.join(PACKAGE_ROOT, "src/abis");
const CONTRACTS_TS = path.join(PACKAGE_ROOT, "src/contracts.ts");
const INDEX_TS = path.join(PACKAGE_ROOT, "src/index.ts");

const CONTRACT_NAMES = [
  "RiptideSwapVMRouter",
  "RiptideRebalanceRouter",
  "RiptideAuctionSettler",
  "RiptideQuoter",
  "RiptideLens",
  "RiptideBatchExecutor",
  "RiptideDemoToken",
  "RiptideVolatilityOracle",
  "RiptideLvrFeeProvider",
];

function readArtifactAbi(name) {
  const artifactPath = path.join(OUT_DIR, `${name}.sol`, `${name}.json`);
  if (!fs.existsSync(artifactPath)) {
    throw new Error(`Missing artifact: ${artifactPath}. Run 'cd contracts && forge build' first.`);
  }
  const artifact = JSON.parse(fs.readFileSync(artifactPath, "utf8"));
  return artifact.abi;
}

function getterName(name) {
  return `get${name}`;
}

function abiExportName(name) {
  return `${name.charAt(0).toLowerCase()}${name.slice(1)}Abi`;
}

function generateAbiFile(name, abi) {
  return [
    "// Auto-generated by scripts/codegen.mjs — do not edit.",
    `export const ${abiExportName(name)} = ${JSON.stringify(abi, null, 2)} as const;`,
    "",
  ].join("\n");
}

function generateContractsTs() {
  const imports = CONTRACT_NAMES.map(
    (name) => `import { ${abiExportName(name)} } from "./abis/${name}.js";`,
  ).join("\n");

  const getters = CONTRACT_NAMES.map((name) => {
    const fn = getterName(name);
    return [
      `export function ${fn}(client: Client, address: Address): GetContractReturnType<typeof ${abiExportName(name)}, Client> {`,
      `  return getContract({ client, address, abi: ${abiExportName(name)} });`,
      "}",
    ].join("\n");
  }).join("\n\n");

  return [
    "// Auto-generated by scripts/codegen.mjs — do not edit.",
    'import { getContract, type Address, type Client, type GetContractReturnType } from "viem";',
    imports,
    "",
    getters,
    "",
  ].join("\n");
}

function generateIndexTs() {
  return [
    "// Auto-generated by scripts/codegen.mjs — do not edit.",
    'export * from "./abis/index.js";',
    'export * from "./contracts.js";',
    'export * from "./manifest.js";',
    'export * from "./manifest.schema.js";',
    'export * from "./explorer.js";',
    'export * from "./rpc.js";',
    'export * from "./networks.js";',
    'export * from "./runtime.js";',
    "",
  ].join("\n");
}

function generateAbisIndex() {
  const exports = CONTRACT_NAMES.map((name) => `export * from "./${name}.js";`).join("\n");
  return [
    "// Auto-generated by scripts/codegen.mjs — do not edit.",
    exports,
    'export * from "./RiptideErrors.js";',
    "",
  ].join("\n");
}

function writeGeneratedFiles() {
  const files = new Map();

  for (const name of CONTRACT_NAMES) {
    const abi = readArtifactAbi(name);
    files.set(path.join(ABI_DIR, `${name}.ts`), generateAbiFile(name, abi));
  }
  files.set(path.join(ABI_DIR, "index.ts"), generateAbisIndex());
  files.set(CONTRACTS_TS, generateContractsTs());
  files.set(INDEX_TS, generateIndexTs());

  return files;
}

function readExisting(relativePath) {
  const fullPath = path.join(PACKAGE_ROOT, relativePath);
  if (!fs.existsSync(fullPath)) return undefined;
  return fs.readFileSync(fullPath, "utf8");
}

function checkGenerated(files) {
  let exitCode = 0;
  for (const [fullPath, content] of files.entries()) {
    const relative = path.relative(PACKAGE_ROOT, fullPath);
    const existing = readExisting(relative);
    if (existing !== content) {
      console.error(`codegen mismatch: ${relative}`);
      exitCode = 1;
    }
  }
  return exitCode;
}

function writeGenerated(files) {
  fs.mkdirSync(ABI_DIR, { recursive: true });
  for (const [fullPath, content] of files.entries()) {
    fs.mkdirSync(path.dirname(fullPath), { recursive: true });
    fs.writeFileSync(fullPath, content, "utf8");
  }
}

function main() {
  const files = writeGeneratedFiles();
  if (process.argv.includes("--check")) {
    return checkGenerated(files);
  }
  writeGenerated(files);
  console.log(`Generated ${files.size} files under packages/contracts/src`);
  return 0;
}

process.exit(main());
