// Auto-generated by scripts/codegen.mjs — do not edit.
import { getContract, type Address, type Client, type GetContractReturnType } from "viem";
import { riptideSwapVMRouterAbi } from "./abis/RiptideSwapVMRouter.js";
import { riptideRebalanceRouterAbi } from "./abis/RiptideRebalanceRouter.js";
import { riptideAuctionSettlerAbi } from "./abis/RiptideAuctionSettler.js";
import { riptideQuoterAbi } from "./abis/RiptideQuoter.js";
import { riptideLensAbi } from "./abis/RiptideLens.js";
import { riptideBatchExecutorAbi } from "./abis/RiptideBatchExecutor.js";
import { riptideDemoTokenAbi } from "./abis/RiptideDemoToken.js";
import { riptideVolatilityOracleAbi } from "./abis/RiptideVolatilityOracle.js";
import { riptideLvrFeeProviderAbi } from "./abis/RiptideLvrFeeProvider.js";

export function getRiptideSwapVMRouter(client: Client, address: Address): GetContractReturnType<typeof riptideSwapVMRouterAbi, Client> {
  return getContract({ client, address, abi: riptideSwapVMRouterAbi });
}

export function getRiptideRebalanceRouter(client: Client, address: Address): GetContractReturnType<typeof riptideRebalanceRouterAbi, Client> {
  return getContract({ client, address, abi: riptideRebalanceRouterAbi });
}

export function getRiptideAuctionSettler(client: Client, address: Address): GetContractReturnType<typeof riptideAuctionSettlerAbi, Client> {
  return getContract({ client, address, abi: riptideAuctionSettlerAbi });
}

export function getRiptideQuoter(client: Client, address: Address): GetContractReturnType<typeof riptideQuoterAbi, Client> {
  return getContract({ client, address, abi: riptideQuoterAbi });
}

export function getRiptideLens(client: Client, address: Address): GetContractReturnType<typeof riptideLensAbi, Client> {
  return getContract({ client, address, abi: riptideLensAbi });
}

export function getRiptideBatchExecutor(client: Client, address: Address): GetContractReturnType<typeof riptideBatchExecutorAbi, Client> {
  return getContract({ client, address, abi: riptideBatchExecutorAbi });
}

export function getRiptideDemoToken(client: Client, address: Address): GetContractReturnType<typeof riptideDemoTokenAbi, Client> {
  return getContract({ client, address, abi: riptideDemoTokenAbi });
}

export function getRiptideVolatilityOracle(client: Client, address: Address): GetContractReturnType<typeof riptideVolatilityOracleAbi, Client> {
  return getContract({ client, address, abi: riptideVolatilityOracleAbi });
}

export function getRiptideLvrFeeProvider(client: Client, address: Address): GetContractReturnType<typeof riptideLvrFeeProviderAbi, Client> {
  return getContract({ client, address, abi: riptideLvrFeeProviderAbi });
}
