import { Address, BigInt, Bytes } from "@graphprotocol/graph-ts";

import { Protocol, Market, Maker, Token } from "../generated/schema";

// AUTO-GENERATED by tools/subgraph/sync-from-manifest.mjs — do not edit manually.
export const PROTOCOL_ID = "31337";
export const DEMO_MARKET_ID = Bytes.fromHexString("0x5fda11de1a2ed0b5d3c2e74823b76e83e05972744e3f0b5695ce173a4fd62251");
export const SWAP_ROUTER = Bytes.fromHexString("0x8b190573374637f144ac8d37375d97fd84cbd3a0");
export const SWAP_ROUTER_ADDRESS = Address.fromString("0x8B190573374637f144AC8D37375d97fd84cBD3a0");
export const BASE_TOKEN = Bytes.fromHexString("0x976c214741b4657bd99dfd38a5c0e3ac5c99d903");
export const QUOTE_TOKEN = Bytes.fromHexString("0x8bee2037448f096900fd9affc427d38ae6cc0350");

export function ensureProtocol(): Protocol {
  let protocol = Protocol.load(PROTOCOL_ID);
  if (protocol == null) {
    protocol = new Protocol(PROTOCOL_ID);
    protocol.chainId = BigInt.fromI32(31337);
    protocol.aqua = Bytes.fromHexString("0xc9952fc93fa9be383ccb39008c786b9f94eac95d");
    protocol.swapRouter = SWAP_ROUTER;
    protocol.rebalanceRouter = Bytes.fromHexString("0x9385556b571ab92bf6dc9a0dbd75429dd4d56f91");
    protocol.batchExecutor = Bytes.fromHexString("0xcd0048a5628b37b8f743cc2fea18817a29e97270");
    protocol.settler = Bytes.fromHexString("0x162700d1613dfec978032a909de02643bc55df1a");
    protocol.quoter = Bytes.fromHexString("0x67ad6ea566ba6b0fc52e97bc25ce46120fdac04c");
    protocol.lens = Bytes.fromHexString("0x114e375b6fcc6d6fcb68c7a1d407e652c54f25fb");
    protocol.totalFillVolume = BigInt.zero();
    protocol.totalRecapture = BigInt.zero();
    protocol.fillCount = BigInt.zero();
    protocol.rebalanceCount = BigInt.zero();
    protocol.save();
  }
  return protocol;
}

export function ensureToken(address: Bytes, symbol: string, decimals: i32): Token {
  const id = address.toHexString();
  let token = Token.load(id);
  if (token == null) {
    token = new Token(id);
    token.symbol = symbol;
    token.decimals = decimals;
    token.save();
  }
  return token;
}

export function ensureMarket(marketId: Bytes): Market {
  const id = marketId.toHexString();
  let market = Market.load(id);
  if (market == null) {
    ensureToken(BASE_TOKEN, "RBASE", 18);
    ensureToken(QUOTE_TOKEN, "RQUOTE", 18);
    market = new Market(id);
    market.baseToken = BASE_TOKEN.toHexString();
    market.quoteToken = QUOTE_TOKEN.toHexString();
    market.fillVolume = BigInt.zero();
    market.recaptureVolume = BigInt.zero();
    market.save();
  }
  return market;
}

export function ensureMaker(address: Address): Maker {
  const id = address.toHexString();
  let maker = Maker.load(id);
  if (maker == null) {
    maker = new Maker(id);
    maker.fillVolume = BigInt.zero();
    maker.recaptureVolume = BigInt.zero();
    maker.save();
  }
  return maker;
}

export function bucketStart(timestamp: BigInt): BigInt {
  const hour = BigInt.fromI32(3600);
  return timestamp.div(hour).times(hour);
}
