import { Address, BigInt, Bytes } from "@graphprotocol/graph-ts";

import { Protocol, Market, Maker, Token } from "../generated/schema";

// AUTO-GENERATED by tools/subgraph/sync-from-manifest.mjs — do not edit manually.
export const PROTOCOL_ID = "31337";
export const DEMO_MARKET_ID = Bytes.fromHexString("0x5fda11de1a2ed0b5d3c2e74823b76e83e05972744e3f0b5695ce173a4fd62251");
export const SWAP_ROUTER = Bytes.fromHexString("0xdc64a140aa3e981100a9beca4e685f962f0cf6c9");
export const SWAP_ROUTER_ADDRESS = Address.fromString("0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9");
export const BASE_TOKEN = Bytes.fromHexString("0x610178da211fef7d417bc0e6fed39f05609ad788");
export const QUOTE_TOKEN = Bytes.fromHexString("0xb7f8bc63bbcad18155201308c8f3540b07f84f5e");

export function ensureProtocol(): Protocol {
  let protocol = Protocol.load(PROTOCOL_ID);
  if (protocol == null) {
    protocol = new Protocol(PROTOCOL_ID);
    protocol.chainId = BigInt.fromI32(31337);
    protocol.aqua = Bytes.fromHexString("0x5fbdb2315678afecb367f032d93f642f64180aa3");
    protocol.swapRouter = SWAP_ROUTER;
    protocol.rebalanceRouter = Bytes.fromHexString("0x5fc8d32690cc91d4c39d9d3abcbd16989f875707");
    protocol.batchExecutor = Bytes.fromHexString("0x8a791620dd6260079bf849dc5567adc3f2fdc318");
    protocol.settler = Bytes.fromHexString("0x0165878a594ca255338adfa4d48449f69242eb8f");
    protocol.quoter = Bytes.fromHexString("0xa513e6e4b8f2a923d98304ec87f64353c4d5c853");
    protocol.lens = Bytes.fromHexString("0x2279b7a0a67db372996a5fab50d91eaa73d2ebe6");
    protocol.totalFillVolume = BigInt.zero();
    protocol.totalRecapture = BigInt.zero();
    protocol.fillCount = BigInt.zero();
    protocol.rebalanceCount = BigInt.zero();
    protocol.save();
  }
  return protocol;
}

export function ensureToken(address: Bytes, symbol: string, decimals: i32): Token {
  const id = address.toHexString();
  let token = Token.load(id);
  if (token == null) {
    token = new Token(id);
    token.symbol = symbol;
    token.decimals = decimals;
    token.save();
  }
  return token;
}

export function ensureMarket(marketId: Bytes): Market {
  const id = marketId.toHexString();
  let market = Market.load(id);
  if (market == null) {
    ensureToken(BASE_TOKEN, "RBASE", 18);
    ensureToken(QUOTE_TOKEN, "RQUOTE", 18);
    market = new Market(id);
    market.baseToken = BASE_TOKEN.toHexString();
    market.quoteToken = QUOTE_TOKEN.toHexString();
    market.fillVolume = BigInt.zero();
    market.recaptureVolume = BigInt.zero();
    market.save();
  }
  return market;
}

export function ensureMaker(address: Address): Maker {
  const id = address.toHexString();
  let maker = Maker.load(id);
  if (maker == null) {
    maker = new Maker(id);
    maker.fillVolume = BigInt.zero();
    maker.recaptureVolume = BigInt.zero();
    maker.save();
  }
  return maker;
}

export function bucketStart(timestamp: BigInt): BigInt {
  const hour = BigInt.fromI32(3600);
  return timestamp.div(hour).times(hour);
}
