import { Address, BigInt, Bytes } from "@graphprotocol/graph-ts";

import { Protocol, Market, Maker, Token } from "../generated/schema";

// AUTO-GENERATED by tools/subgraph/sync-from-manifest.mjs — do not edit manually.
export const PROTOCOL_ID = "31337";
export const DEMO_MARKET_ID = Bytes.fromHexString("0xe0cb43934dd2863d5136dd5fb1282d29617d08194465d73d8bfa87951ab9a598");
export const SWAP_ROUTER = Bytes.fromHexString("0x0000000000000000000000000000000000000002");
export const SWAP_ROUTER_ADDRESS = Address.fromString("0x0000000000000000000000000000000000000002");
export const BASE_TOKEN = Bytes.fromHexString("0x0000000000000000000000000000000000000011");
export const QUOTE_TOKEN = Bytes.fromHexString("0x0000000000000000000000000000000000000012");

export function ensureProtocol(): Protocol {
  let protocol = Protocol.load(PROTOCOL_ID);
  if (protocol == null) {
    protocol = new Protocol(PROTOCOL_ID);
    protocol.chainId = BigInt.fromI32(31337);
    protocol.aqua = Bytes.fromHexString("0x0000000000000000000000000000000000000001");
    protocol.swapRouter = SWAP_ROUTER;
    protocol.rebalanceRouter = Bytes.fromHexString("0x0000000000000000000000000000000000000003");
    protocol.batchExecutor = Bytes.fromHexString("0x000000000000000000000000000000000000000a");
    protocol.settler = Bytes.fromHexString("0x0000000000000000000000000000000000000007");
    protocol.quoter = Bytes.fromHexString("0x0000000000000000000000000000000000000008");
    protocol.lens = Bytes.fromHexString("0x0000000000000000000000000000000000000009");
    protocol.totalFillVolume = BigInt.zero();
    protocol.totalRecapture = BigInt.zero();
    protocol.fillCount = BigInt.zero();
    protocol.rebalanceCount = BigInt.zero();
    protocol.save();
  }
  return protocol;
}

export function ensureToken(address: Bytes, symbol: string, decimals: i32): Token {
  const id = address.toHexString();
  let token = Token.load(id);
  if (token == null) {
    token = new Token(id);
    token.symbol = symbol;
    token.decimals = decimals;
    token.save();
  }
  return token;
}

export function ensureMarket(marketId: Bytes): Market {
  const id = marketId.toHexString();
  let market = Market.load(id);
  if (market == null) {
    ensureToken(BASE_TOKEN, "RBASE", 18);
    ensureToken(QUOTE_TOKEN, "RQUOTE", 18);
    market = new Market(id);
    market.baseToken = BASE_TOKEN.toHexString();
    market.quoteToken = QUOTE_TOKEN.toHexString();
    market.fillVolume = BigInt.zero();
    market.recaptureVolume = BigInt.zero();
    market.save();
  }
  return market;
}

export function ensureMaker(address: Address): Maker {
  const id = address.toHexString();
  let maker = Maker.load(id);
  if (maker == null) {
    maker = new Maker(id);
    maker.fillVolume = BigInt.zero();
    maker.recaptureVolume = BigInt.zero();
    maker.save();
  }
  return maker;
}

export function bucketStart(timestamp: BigInt): BigInt {
  const hour = BigInt.fromI32(3600);
  return timestamp.div(hour).times(hour);
}
