// Auto-generated by scripts/codegen.mjs — do not edit.
export const riptideVolatilityOracleAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "router_",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "swapRouter_",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "volIndexer_",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "assertFeedFresh",
    "inputs": [
      {
        "name": "feed",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "maxStaleness",
        "type": "uint16",
        "internalType": "uint16"
      }
    ],
    "outputs": [],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "configureStrategy",
    "inputs": [
      {
        "name": "strategyKey",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "fee",
        "type": "tuple",
        "internalType": "struct RiptideTypes.FeePolicy",
        "components": [
          {
            "name": "feeMin",
            "type": "uint24",
            "internalType": "uint24"
          },
          {
            "name": "feeMax",
            "type": "uint24",
            "internalType": "uint24"
          },
          {
            "name": "lambda",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "kp",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "ki",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "iMax",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "sigmaMin",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "sigmaMax",
            "type": "uint64",
            "internalType": "uint64"
          }
        ]
      },
      {
        "name": "oracle",
        "type": "tuple",
        "internalType": "struct RiptideTypes.OracleConfig",
        "components": [
          {
            "name": "feed",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "decimals",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "maxStaleness",
            "type": "uint16",
            "internalType": "uint16"
          }
        ]
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "observe",
    "inputs": [
      {
        "name": "strategyKey",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "priceWad",
        "type": "uint128",
        "internalType": "uint128"
      },
      {
        "name": "ts",
        "type": "uint40",
        "internalType": "uint40"
      },
      {
        "name": "isStatic",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "outputs": [
      {
        "name": "sigmaWadOut",
        "type": "uint128",
        "internalType": "uint128"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "observeRange",
    "inputs": [
      {
        "name": "strategyKey",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "h",
        "type": "uint128",
        "internalType": "uint128"
      },
      {
        "name": "l",
        "type": "uint128",
        "internalType": "uint128"
      },
      {
        "name": "c",
        "type": "uint128",
        "internalType": "uint128"
      },
      {
        "name": "o",
        "type": "uint128",
        "internalType": "uint128"
      },
      {
        "name": "ts",
        "type": "uint40",
        "internalType": "uint40"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint128",
        "internalType": "uint128"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "router",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "sigmaWad",
    "inputs": [
      {
        "name": "strategyKey",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint128",
        "internalType": "uint128"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "swapRouter",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "varWad",
    "inputs": [
      {
        "name": "strategyKey",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint128",
        "internalType": "uint128"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "volIndexer",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "error",
    "name": "RiptideLogInputOutOfDomain",
    "inputs": [
      {
        "name": "inputWad",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "RiptideMathDivisionByZero",
    "inputs": []
  },
  {
    "type": "error",
    "name": "RiptideMathOverflow",
    "inputs": []
  },
  {
    "type": "error",
    "name": "RiptideStaleOracleRound",
    "inputs": [
      {
        "name": "updatedAt",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "maxStaleness",
        "type": "uint16",
        "internalType": "uint16"
      }
    ]
  },
  {
    "type": "error",
    "name": "RiptideUnauthorizedObserver",
    "inputs": [
      {
        "name": "caller",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "RiptideZeroAddress",
    "inputs": []
  }
] as const;
