// Auto-generated by scripts/codegen.mjs — do not edit.
export const riptideRebalanceRouterAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "aqua",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "weth",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "owner",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "name",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "version",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "kernel",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "oracle",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "feeProvider",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "receive",
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "AQUA",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IAqua"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "FEE_PROVIDER",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IRiptideLvrFeeProvider"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "KERNEL",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IRiptideRebalanceKernel"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "MODULE",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract RiptideRebalanceModule"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "ORACLE",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IRiptideVolatilityOracle"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "ORDER_TYPEHASH",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "advanceControllerForRebalance",
    "inputs": [
      {
        "name": "strategyKey",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "asView",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract ISwapVM"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "buildRebalanceOrder",
    "inputs": [
      {
        "name": "maker",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "strategy",
        "type": "tuple",
        "internalType": "struct RiptideTypes.Strategy",
        "components": [
          {
            "name": "maker",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "baseToken",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "quoteToken",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "reserveBaseWad",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "reserveQuoteWad",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "fee",
            "type": "tuple",
            "internalType": "struct RiptideTypes.FeePolicy",
            "components": [
              {
                "name": "feeMin",
                "type": "uint24",
                "internalType": "uint24"
              },
              {
                "name": "feeMax",
                "type": "uint24",
                "internalType": "uint24"
              },
              {
                "name": "lambda",
                "type": "uint64",
                "internalType": "uint64"
              },
              {
                "name": "kp",
                "type": "uint64",
                "internalType": "uint64"
              },
              {
                "name": "ki",
                "type": "uint64",
                "internalType": "uint64"
              },
              {
                "name": "iMax",
                "type": "uint64",
                "internalType": "uint64"
              },
              {
                "name": "sigmaMin",
                "type": "uint64",
                "internalType": "uint64"
              },
              {
                "name": "sigmaMax",
                "type": "uint64",
                "internalType": "uint64"
              }
            ]
          },
          {
            "name": "auction",
            "type": "tuple",
            "internalType": "struct RiptideTypes.AuctionPolicy",
            "components": [
              {
                "name": "beta",
                "type": "uint64",
                "internalType": "uint64"
              },
              {
                "name": "duration",
                "type": "uint16",
                "internalType": "uint16"
              },
              {
                "name": "decay",
                "type": "uint64",
                "internalType": "uint64"
              },
              {
                "name": "antiSandwichPeriod",
                "type": "uint16",
                "internalType": "uint16"
              }
            ]
          },
          {
            "name": "oracle",
            "type": "tuple",
            "internalType": "struct RiptideTypes.OracleConfig",
            "components": [
              {
                "name": "feed",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "decimals",
                "type": "uint8",
                "internalType": "uint8"
              },
              {
                "name": "maxStaleness",
                "type": "uint16",
                "internalType": "uint16"
              }
            ]
          },
          {
            "name": "feeProvider",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "salt",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ]
      },
      {
        "name": "deadline",
        "type": "uint40",
        "internalType": "uint40"
      },
      {
        "name": "outWad",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "useAuctionBalanceIn",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "outputs": [
      {
        "name": "order",
        "type": "tuple",
        "internalType": "struct ISwapVM.Order",
        "components": [
          {
            "name": "maker",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "traits",
            "type": "uint256",
            "internalType": "MakerTraits"
          },
          {
            "name": "data",
            "type": "bytes",
            "internalType": "bytes"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "buildRebalanceOrderWithAuctionStart",
    "inputs": [
      {
        "name": "maker",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "strategy",
        "type": "tuple",
        "internalType": "struct RiptideTypes.Strategy",
        "components": [
          {
            "name": "maker",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "baseToken",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "quoteToken",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "reserveBaseWad",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "reserveQuoteWad",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "fee",
            "type": "tuple",
            "internalType": "struct RiptideTypes.FeePolicy",
            "components": [
              {
                "name": "feeMin",
                "type": "uint24",
                "internalType": "uint24"
              },
              {
                "name": "feeMax",
                "type": "uint24",
                "internalType": "uint24"
              },
              {
                "name": "lambda",
                "type": "uint64",
                "internalType": "uint64"
              },
              {
                "name": "kp",
                "type": "uint64",
                "internalType": "uint64"
              },
              {
                "name": "ki",
                "type": "uint64",
                "internalType": "uint64"
              },
              {
                "name": "iMax",
                "type": "uint64",
                "internalType": "uint64"
              },
              {
                "name": "sigmaMin",
                "type": "uint64",
                "internalType": "uint64"
              },
              {
                "name": "sigmaMax",
                "type": "uint64",
                "internalType": "uint64"
              }
            ]
          },
          {
            "name": "auction",
            "type": "tuple",
            "internalType": "struct RiptideTypes.AuctionPolicy",
            "components": [
              {
                "name": "beta",
                "type": "uint64",
                "internalType": "uint64"
              },
              {
                "name": "duration",
                "type": "uint16",
                "internalType": "uint16"
              },
              {
                "name": "decay",
                "type": "uint64",
                "internalType": "uint64"
              },
              {
                "name": "antiSandwichPeriod",
                "type": "uint16",
                "internalType": "uint16"
              }
            ]
          },
          {
            "name": "oracle",
            "type": "tuple",
            "internalType": "struct RiptideTypes.OracleConfig",
            "components": [
              {
                "name": "feed",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "decimals",
                "type": "uint8",
                "internalType": "uint8"
              },
              {
                "name": "maxStaleness",
                "type": "uint16",
                "internalType": "uint16"
              }
            ]
          },
          {
            "name": "feeProvider",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "salt",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ]
      },
      {
        "name": "deadline",
        "type": "uint40",
        "internalType": "uint40"
      },
      {
        "name": "outWad",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "useAuctionBalanceIn",
        "type": "bool",
        "internalType": "bool"
      },
      {
        "name": "auctionStart",
        "type": "uint40",
        "internalType": "uint40"
      }
    ],
    "outputs": [
      {
        "name": "order",
        "type": "tuple",
        "internalType": "struct ISwapVM.Order",
        "components": [
          {
            "name": "maker",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "traits",
            "type": "uint256",
            "internalType": "MakerTraits"
          },
          {
            "name": "data",
            "type": "bytes",
            "internalType": "bytes"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "eip712Domain",
    "inputs": [],
    "outputs": [
      {
        "name": "fields",
        "type": "bytes1",
        "internalType": "bytes1"
      },
      {
        "name": "name",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "version",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "chainId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "verifyingContract",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "salt",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "extensions",
        "type": "uint256[]",
        "internalType": "uint256[]"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "emitRebalanceSettled",
    "inputs": [
      {
        "name": "strategyKey",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "maker",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "resolver",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "marketId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "tokenIn",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "tokenOut",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "executedInWad",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "staleInWad",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "surplusWad",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "retainToLPWad",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "payToResolverWad",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "revealedPriceWad",
        "type": "uint128",
        "internalType": "uint128"
      },
      {
        "name": "versionAfter",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "orderHash",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "hash",
    "inputs": [
      {
        "name": "order",
        "type": "tuple",
        "internalType": "struct ISwapVM.Order",
        "components": [
          {
            "name": "maker",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "traits",
            "type": "uint256",
            "internalType": "MakerTraits"
          },
          {
            "name": "data",
            "type": "bytes",
            "internalType": "bytes"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "observeForRebalance",
    "inputs": [
      {
        "name": "strategyKey",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "priceWad",
        "type": "uint128",
        "internalType": "uint128"
      },
      {
        "name": "ts",
        "type": "uint40",
        "internalType": "uint40"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "orderStrategyKey",
    "inputs": [
      {
        "name": "orderHash",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "owner",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "pullForRebalance",
    "inputs": [
      {
        "name": "maker",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "strategyHash",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "amount",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "to",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "quote",
    "inputs": [
      {
        "name": "order",
        "type": "tuple",
        "internalType": "struct ISwapVM.Order",
        "components": [
          {
            "name": "maker",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "traits",
            "type": "uint256",
            "internalType": "MakerTraits"
          },
          {
            "name": "data",
            "type": "bytes",
            "internalType": "bytes"
          }
        ]
      },
      {
        "name": "tokenIn",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "tokenOut",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "amount",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "takerTraitsAndData",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [
      {
        "name": "amountIn",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "amountOut",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "orderHash",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "rebalanceAuctionStart",
    "inputs": [
      {
        "name": "strategyKey",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint40",
        "internalType": "uint40"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "registerStrategy",
    "inputs": [
      {
        "name": "strategyKey",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "orderHash",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "marketId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "renounceOwnership",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "rescueFunds",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "contract IERC20"
      },
      {
        "name": "amount",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "runtimeState",
    "inputs": [
      {
        "name": "strategyKey",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct RiptideTypes.ControllerState",
        "components": [
          {
            "name": "feeReported",
            "type": "uint24",
            "internalType": "uint24"
          },
          {
            "name": "integral",
            "type": "int192",
            "internalType": "int192"
          },
          {
            "name": "varWad",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "lastObsTs",
            "type": "uint40",
            "internalType": "uint40"
          },
          {
            "name": "lastPriceWad",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "lastRebalanceTs",
            "type": "uint40",
            "internalType": "uint40"
          },
          {
            "name": "version",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "initialized",
            "type": "bool",
            "internalType": "bool"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "setRebalanceAuctionStart",
    "inputs": [
      {
        "name": "strategyKey",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "auctionStart",
        "type": "uint40",
        "internalType": "uint40"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "swap",
    "inputs": [
      {
        "name": "order",
        "type": "tuple",
        "internalType": "struct ISwapVM.Order",
        "components": [
          {
            "name": "maker",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "traits",
            "type": "uint256",
            "internalType": "MakerTraits"
          },
          {
            "name": "data",
            "type": "bytes",
            "internalType": "bytes"
          }
        ]
      },
      {
        "name": "tokenIn",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "tokenOut",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "amount",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "takerTraitsAndData",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [
      {
        "name": "amountIn",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "amountOut",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "orderHash",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "transferOwnership",
    "inputs": [
      {
        "name": "newOwner",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "event",
    "name": "AuctionSettled",
    "inputs": [
      {
        "name": "strategyKey",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "settledBy",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "maker",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "outWad",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "amountInWad",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "surplusWad",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "payToResolverWad",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "retainToLPWad",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "EIP712DomainChanged",
    "inputs": [],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "FeeControllerUpdated",
    "inputs": [
      {
        "name": "strategyKey",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "sigmaWad",
        "type": "uint128",
        "indexed": false,
        "internalType": "uint128"
      },
      {
        "name": "feeTarget",
        "type": "uint24",
        "indexed": false,
        "internalType": "uint24"
      },
      {
        "name": "feeReported",
        "type": "uint24",
        "indexed": false,
        "internalType": "uint24"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "OwnershipTransferred",
    "inputs": [
      {
        "name": "previousOwner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "newOwner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "RebalanceSettled",
    "inputs": [
      {
        "name": "strategyKey",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "maker",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "resolver",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "marketId",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "tokenIn",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "tokenOut",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "executedInWad",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "staleInWad",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "surplusWad",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "retainToLPWad",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "payToResolverWad",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "revealedPriceWad",
        "type": "uint128",
        "indexed": false,
        "internalType": "uint128"
      },
      {
        "name": "versionAfter",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "RiptideRebalanceExecuted",
    "inputs": [
      {
        "name": "orderHash",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "RouteExecuted",
    "inputs": [
      {
        "name": "routeId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "marketId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "payer",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "recipient",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "kind",
        "type": "uint8",
        "indexed": false,
        "internalType": "enum RiptideTypes.QuoteKind"
      },
      {
        "name": "tokenIn",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "tokenOut",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "amountIn",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "amountOut",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "limit",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "fillCount",
        "type": "uint16",
        "indexed": false,
        "internalType": "uint16"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "StrategyRuntimeInitialized",
    "inputs": [
      {
        "name": "strategyKey",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "marketId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "maker",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "strategyHash",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "reserveBaseWad",
        "type": "uint128",
        "indexed": false,
        "internalType": "uint128"
      },
      {
        "name": "reserveQuoteWad",
        "type": "uint128",
        "indexed": false,
        "internalType": "uint128"
      },
      {
        "name": "version",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "SwapFilled",
    "inputs": [
      {
        "name": "routeId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "strategyKey",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "maker",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "marketId",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "tokenIn",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "tokenOut",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "amountIn",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "amountOut",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "feeBpsApplied",
        "type": "uint24",
        "indexed": false,
        "internalType": "uint24"
      },
      {
        "name": "sigmaWad",
        "type": "uint128",
        "indexed": false,
        "internalType": "uint128"
      },
      {
        "name": "reserveBaseAfterWad",
        "type": "uint128",
        "indexed": false,
        "internalType": "uint128"
      },
      {
        "name": "reserveQuoteAfterWad",
        "type": "uint128",
        "indexed": false,
        "internalType": "uint128"
      },
      {
        "name": "versionAfter",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Swapped",
    "inputs": [
      {
        "name": "orderHash",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "maker",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "taker",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "tokenIn",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "tokenOut",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "amountIn",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "amountOut",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "AquaBalanceInsufficientAfterTakerPush",
    "inputs": [
      {
        "name": "balance",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "preBalance",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "amount",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "amountNetPulled",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "BadSignature",
    "inputs": [
      {
        "name": "maker",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "orderHash",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "signature",
        "type": "bytes",
        "internalType": "bytes"
      }
    ]
  },
  {
    "type": "error",
    "name": "ControlsMissingDeadlineArg",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ControlsMissingMinAmountArg",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ControlsMissingMinShareArg",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ControlsMissingTokenArg",
    "inputs": []
  },
  {
    "type": "error",
    "name": "DeadlineReached",
    "inputs": [
      {
        "name": "taker",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "deadline",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "DecayShouldBeCalledBeforeSwapAmountsComputation",
    "inputs": [
      {
        "name": "amountIn",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "amountOut",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "ETHTransferFailed",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ETHTransferFailed",
    "inputs": []
  },
  {
    "type": "error",
    "name": "EthDepositRejected",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ForceApproveFailed",
    "inputs": []
  },
  {
    "type": "error",
    "name": "IRiptideRebalanceAppUnauthorized",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InsufficientBalance",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidShortString",
    "inputs": []
  },
  {
    "type": "error",
    "name": "JumpMissingNextPCArg",
    "inputs": []
  },
  {
    "type": "error",
    "name": "MakerTraitsCustomReceiverIsIncompatibleWithAqua",
    "inputs": []
  },
  {
    "type": "error",
    "name": "MakerTraitsTokenInAndTokenOutMustBeDifferent",
    "inputs": []
  },
  {
    "type": "error",
    "name": "MakerTraitsUnwrapIsIncompatibleWithAqua",
    "inputs": []
  },
  {
    "type": "error",
    "name": "MakerTraitsZeroAmountInNotAllowed",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OwnableInvalidOwner",
    "inputs": [
      {
        "name": "owner",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "OwnableUnauthorizedAccount",
    "inputs": [
      {
        "name": "account",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "RiptideAuctionMustPrecedeSwap",
    "inputs": [
      {
        "name": "amountIn",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "amountOut",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "RiptideAuctionWindowExpired",
    "inputs": [
      {
        "name": "currentTime",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "deadline",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "RiptideUnauthorizedResolver",
    "inputs": [
      {
        "name": "caller",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "RunLoopExcessiveCall",
    "inputs": [
      {
        "name": "pc",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "programLength",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "SafeCastOverflowedUintDowncast",
    "inputs": [
      {
        "name": "bits",
        "type": "uint8",
        "internalType": "uint8"
      },
      {
        "name": "value",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "SafeTransferFailed",
    "inputs": []
  },
  {
    "type": "error",
    "name": "SafeTransferFromFailed",
    "inputs": []
  },
  {
    "type": "error",
    "name": "StringTooLong",
    "inputs": [
      {
        "name": "str",
        "type": "string",
        "internalType": "string"
      }
    ]
  },
  {
    "type": "error",
    "name": "TakerTokenBalanceIsLessThanRequired",
    "inputs": [
      {
        "name": "taker",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "balance",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "minAmount",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "TakerTokenBalanceIsZero",
    "inputs": [
      {
        "name": "taker",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "TakerTokenBalanceSupplyShareIsLessThanRequired",
    "inputs": [
      {
        "name": "taker",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "balance",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "totalSupply",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "minShareE18",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "TakerTraitsAmountOutMustBeGreaterThanZero",
    "inputs": [
      {
        "name": "amountOut",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "TakerTraitsDeadlineExpired",
    "inputs": []
  },
  {
    "type": "error",
    "name": "TakerTraitsExceedingMaxInputAmount",
    "inputs": [
      {
        "name": "amountIn",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "amountInMax",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "TakerTraitsInsufficientMinOutputAmount",
    "inputs": [
      {
        "name": "amountOut",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "amountOutMin",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "TakerTraitsNonExactThresholdAmountIn",
    "inputs": [
      {
        "name": "amountIn",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "amountThreshold",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "TakerTraitsNonExactThresholdAmountOut",
    "inputs": [
      {
        "name": "amountOut",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "amountThreshold",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "TakerTraitsTakerAmountInMismatch",
    "inputs": [
      {
        "name": "takerAmount",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "computedAmount",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "TakerTraitsTakerAmountOutMismatch",
    "inputs": [
      {
        "name": "takerAmount",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "computedAmount",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "TxOriginTokenBalanceIsZero",
    "inputs": [
      {
        "name": "txOrigin",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "UnexpectedLock",
    "inputs": []
  },
  {
    "type": "error",
    "name": "XYCSwapRecomputeDetected",
    "inputs": []
  },
  {
    "type": "error",
    "name": "XYCSwapRequiresBothBalancesNonZero",
    "inputs": [
      {
        "name": "balanceIn",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "balanceOut",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  }
] as const;
