// Auto-generated by scripts/codegen.mjs — do not edit.
export const riptideLensAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "swapRouter",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "rebalanceRouter",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "aqua",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "feeProvider",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "oracle",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "AQUA",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IAqua"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "FEE_PROVIDER",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IRiptideLvrFeeProvider"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "ORACLE",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IRiptideVolatilityOracle"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "REBALANCE_ROUTER",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract RiptideRebalanceRouter"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "SWAP_ROUTER",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract RiptideSwapVMRouter"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "strategyState",
    "inputs": [
      {
        "name": "maker",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "strategyHash",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "base",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "quote",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "state",
        "type": "tuple",
        "internalType": "struct IRiptideLens.StrategyState",
        "components": [
          {
            "name": "runtime",
            "type": "tuple",
            "internalType": "struct RiptideTypes.ControllerState",
            "components": [
              {
                "name": "feeReported",
                "type": "uint24",
                "internalType": "uint24"
              },
              {
                "name": "integral",
                "type": "int192",
                "internalType": "int192"
              },
              {
                "name": "varWad",
                "type": "uint128",
                "internalType": "uint128"
              },
              {
                "name": "lastObsTs",
                "type": "uint40",
                "internalType": "uint40"
              },
              {
                "name": "lastPriceWad",
                "type": "uint128",
                "internalType": "uint128"
              },
              {
                "name": "lastRebalanceTs",
                "type": "uint40",
                "internalType": "uint40"
              },
              {
                "name": "version",
                "type": "uint64",
                "internalType": "uint64"
              },
              {
                "name": "initialized",
                "type": "bool",
                "internalType": "bool"
              }
            ]
          },
          {
            "name": "feeReported",
            "type": "uint24",
            "internalType": "uint24"
          },
          {
            "name": "sigmaWad",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "aquaBase",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "aquaQuote",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "walletBase",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "walletQuote",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "allowanceBase",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "allowanceQuote",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "swapVersion",
            "type": "uint64",
            "internalType": "uint64"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "error",
    "name": "RiptideStrategyNotActive",
    "inputs": [
      {
        "name": "strategyHash",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "RiptideZeroAddress",
    "inputs": []
  }
] as const;
