// Auto-generated by scripts/codegen.mjs — do not edit.
export const riptideAuctionSettlerAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "rebalanceRouter",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "kernel",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "KERNEL",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract RiptideRebalanceKernel"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "REBALANCE_ROUTER",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract RiptideRebalanceRouter"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "settleRebalance",
    "inputs": [
      {
        "name": "maker",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "s",
        "type": "tuple",
        "internalType": "struct RiptideTypes.Strategy",
        "components": [
          {
            "name": "maker",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "baseToken",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "quoteToken",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "reserveBaseWad",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "reserveQuoteWad",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "fee",
            "type": "tuple",
            "internalType": "struct RiptideTypes.FeePolicy",
            "components": [
              {
                "name": "feeMin",
                "type": "uint24",
                "internalType": "uint24"
              },
              {
                "name": "feeMax",
                "type": "uint24",
                "internalType": "uint24"
              },
              {
                "name": "lambda",
                "type": "uint64",
                "internalType": "uint64"
              },
              {
                "name": "kp",
                "type": "uint64",
                "internalType": "uint64"
              },
              {
                "name": "ki",
                "type": "uint64",
                "internalType": "uint64"
              },
              {
                "name": "iMax",
                "type": "uint64",
                "internalType": "uint64"
              },
              {
                "name": "sigmaMin",
                "type": "uint64",
                "internalType": "uint64"
              },
              {
                "name": "sigmaMax",
                "type": "uint64",
                "internalType": "uint64"
              }
            ]
          },
          {
            "name": "auction",
            "type": "tuple",
            "internalType": "struct RiptideTypes.AuctionPolicy",
            "components": [
              {
                "name": "beta",
                "type": "uint64",
                "internalType": "uint64"
              },
              {
                "name": "duration",
                "type": "uint16",
                "internalType": "uint16"
              },
              {
                "name": "decay",
                "type": "uint64",
                "internalType": "uint64"
              },
              {
                "name": "antiSandwichPeriod",
                "type": "uint16",
                "internalType": "uint16"
              }
            ]
          },
          {
            "name": "oracle",
            "type": "tuple",
            "internalType": "struct RiptideTypes.OracleConfig",
            "components": [
              {
                "name": "feed",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "decimals",
                "type": "uint8",
                "internalType": "uint8"
              },
              {
                "name": "maxStaleness",
                "type": "uint16",
                "internalType": "uint16"
              }
            ]
          },
          {
            "name": "feeProvider",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "salt",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ]
      },
      {
        "name": "outWad",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "maxInWad",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "deadline",
        "type": "uint40",
        "internalType": "uint40"
      }
    ],
    "outputs": [
      {
        "name": "result",
        "type": "tuple",
        "internalType": "struct RiptideTypes.RebalanceResult",
        "components": [
          {
            "name": "surplusWad",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "payToResolver",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "retainToLP",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "error",
    "name": "RiptideDeadlineExpired",
    "inputs": [
      {
        "name": "deadline",
        "type": "uint40",
        "internalType": "uint40"
      },
      {
        "name": "timestamp",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "RiptideRebalanceAuctionStartMissing",
    "inputs": [
      {
        "name": "strategyKey",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "RiptideSlippageExceeded",
    "inputs": [
      {
        "name": "actual",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "limit",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "RiptideZeroAddress",
    "inputs": []
  },
  {
    "type": "error",
    "name": "SafeCastOverflowedUintDowncast",
    "inputs": [
      {
        "name": "bits",
        "type": "uint8",
        "internalType": "uint8"
      },
      {
        "name": "value",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "SafeERC20FailedOperation",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "TakerTraitsMissingHasPreTransferInFlag",
    "inputs": []
  },
  {
    "type": "error",
    "name": "TakerTraitsMissingHasPreTransferOutFlag",
    "inputs": []
  },
  {
    "type": "error",
    "name": "TakerTraitsThresholdLengthInvalid",
    "inputs": [
      {
        "name": "threshold",
        "type": "bytes",
        "internalType": "bytes"
      }
    ]
  }
] as const;
